name: Deploy static site via SFTP

on:
  push:
    branches: [ master ]
    paths:
      - "index.html"
      - "stylesheets/**"
      - "javascripts/**"
      - "images/**"
      - "fonts/**"
      - "data/**"
  workflow_dispatch:

concurrency:
  group: sftp-deploy
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Prepare deploy folder
        run: |
          rm -rf deploy
          mkdir -p deploy
          cp -v index.html deploy/ || true
          for d in stylesheets javascripts images fonts data; do
            if [ -d "$d" ]; then
              mkdir -p "deploy/$d"
              rsync -a "$d"/ "deploy/$d"/
            fi
          done

      - name: Install sshpass
        run: |
          sudo apt-get update
          sudo apt-get install -y sshpass

      - name: Deploy with rsync over SSH
        env:
          SSHPASS: ${{ secrets.SFTP_PASSWORD }}
        run: |
          sshpass -e rsync -avz --delete \
            -e "ssh -o StrictHostKeyChecking=no -p ${{ secrets.SFTP_PORT }}" \
            --exclude='.git*' \
            --exclude='.DS_Store' \
            ./deploy/ \
            ${{ secrets.SFTP_USERNAME }}@${{ secrets.SFTP_HOST }}:${{ secrets.SFTP_REMOTE_PATH }}/

